version: "3"

services:
  

  mysql:
    image: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo

volumes:
  mysqldata:
    driver: local
